# Generated by Django 5.0.2 on 2024-03-21 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCreateOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_requester', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_org', to='app.university')),
            ],
            options={
                'unique_together': {('requester', 'org_name', 'university')},
            },
        ),
        migrations.CreateModel(
            name='PendingJoinOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_org', to='app.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requester', 'organization')},
            },
        ),
    ]
