# Generated by Django 5.0.2 on 2024-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pendingcreateorg_pendingjoinorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcreateorg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingjoinorg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
