# Generated by Django 5.0.3 on 2024-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pendingcreateorg_id_alter_pendingjoinorg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='university',
        ),
    ]
