# Generated by Django 5.0.2 on 2024-03-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pendingcreateorg_id_alter_pendingjoinorg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=90),
        ),
    ]
