# Generated by Django 5.0.2 on 2024-04-01 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='app.university'),
        ),
        migrations.CreateModel(
            name='OrgRegisteredEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='app.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_org', to='app.organization')),
            ],
        ),
    ]
