# Generated by Django 5.0.2 on 2024-04-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_university_orgregisteredevent'),
        ('app', '0006_plot_university'),
    ]

    operations = [
    ]
