# Generated by Django 5.0.4 on 2024-04-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.plot'),
            preserve_default=False,
        ),
    ]
