# Generated by Django 5.0.2 on 2024-04-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_event_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='section',
        ),
        migrations.AlterField(
            model_name='event',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_plot', to='app.plot'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
