# Generated by Django 4.2.10 on 2024-04-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_plot_section_alter_event_plot_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='app.plot')),
            ],
        ),
    ]
