# Generated by Django 5.0.2 on 2024-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_plot_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='name',
            field=models.CharField(default='Aggie Plot', max_length=250, null=True),
        ),
    ]
