# Generated by Django 5.0.2 on 2024-04-08 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_plot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisteredEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time_registered', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_member_event', to='app.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_member', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_member_org', to='app.organization')),
            ],
        ),
    ]
