# Generated by Django 5.0.2 on 2024-04-11 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_first_name_user_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentregisteredevent',
            name='date_time_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
